{
 "title": "Hardware",
 "tags": [ "hardware" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "SHOW TAG VALUES FROM \"sensors\" WITH KEY = \"host\""
   },
   {
    "name": "chip",
    "label": "Chip",
    "query": "SHOW TAG VALUES FROM sensors WITH KEY = \"chip\""
   },
   {
    "name": "feature",
    "label": "Feature",
    "query": "SHOW TAG VALUES FROM sensors WITH KEY = \"feature\""
   },
   {
    "name": "fan",
    "label": "Fan",
    "query": "SHOW TAG VALUES FROM ipmi_sensor WITH KEY = \"name\" WHERE \"name\" =~ /fan.+rpm/"
   },
   {
    "name": "current",
    "label": "Current",
    "query": "SHOW TAG VALUES FROM ipmi_sensor WITH KEY = \"name\" WHERE \"name\" =~ /^current/"
   },
   {
    "name": "disk_id",
    "label": "Disk ID",
    "query": "SHOW TAG VALUES FROM omreport_custom WITH KEY = \"disk_id\""
   },
   {
    "name": "memory_id",
    "label": "Memory ID",
    "query": "SHOW TAG VALUES FROM omreport_custom WITH KEY = \"memory_id\""
   },
   {
    "name": "ps_id",
    "label": "PowerSupply ID",
    "query": "SHOW TAG VALUES FROM omreport_custom WITH KEY = \"ps_id\""
   }
  ]
 },
 "panels": [
  { "title": "Current Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  { "title": "Disk Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Disk State - $node",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "repeat": "node",
   "targets": [
    {
     "alias": "Disk State - $tag_disk_id",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "disk_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "omreport_custom",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "disk_id", "operator": "=~", "value": "/^$disk_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk State - $node",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "targets": [
    {
     "alias": "Disk State - $tag_disk_id",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "disk_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "omreport_custom",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "disk_id", "operator": "=~", "value": "/^$disk_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk State - $node",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "alias": "Disk State - $tag_disk_id",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "disk_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "omreport_custom",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "disk_id", "operator": "=~", "value": "/^$disk_id$/" }
     ]
    }
   ]
  },
  { "title": "Memory Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Errors - $node",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 11 },
   "repeat": "node",
   "targets": [
    {
     "alias": "Memory Errors - $tag_memory_id",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "memory_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "omreport_custom",
     "select": [
      [
       { "params": [ "error_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "memory_id", "operator": "=~", "value": "/^$memory_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Errors - $node",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "alias": "Memory Errors - $tag_memory_id",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "memory_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "omreport_custom",
     "select": [
      [
       { "params": [ "error_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "memory_id", "operator": "=~", "value": "/^$memory_id$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Errors - $node",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "alias": "Memory Errors - $tag_memory_id",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "memory_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "omreport_custom",
     "select": [
      [
       { "params": [ "error_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "memory_id", "operator": "=~", "value": "/^$memory_id$/" }
     ]
    }
   ]
  },
  { "title": "PowerSupply Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "PowerSupply Status - $node",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "repeat": "node",
   "targets": [
    {
     "alias": "PowerSupply State - $tag_ps_id",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "ps_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "omreport_custom",
     "select": [
      [
       { "params": [ "ps_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "ps_id", "operator": "=~", "value": "/^$ps_id$/" }
     ]
    }
   ]
  },
  {
   "title": "PowerSupply Status - $node",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "alias": "PowerSupply State - $tag_ps_id",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "ps_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "omreport_custom",
     "select": [
      [
       { "params": [ "ps_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "ps_id", "operator": "=~", "value": "/^$ps_id$/" }
     ]
    }
   ]
  },
  {
   "title": "PowerSupply Status - $node",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "alias": "PowerSupply State - $tag_ps_id",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "ps_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "omreport_custom",
     "select": [
      [
       { "params": [ "ps_state" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" },
      { "condition": "AND", "key": "ps_id", "operator": "=~", "value": "/^$ps_id$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Temp - $node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "repeat": "node",
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "CPU Temp - $tag_chip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chip" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "query": "SELECT mean(\"temp_input\") FROM \"compunaut_one_year\".\"sensors\" WHERE (\"host\" =~ /^$node$/ AND \"chip\" =~ /^$chip$/ AND \"feature\" = 'core_0') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "temp_input" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "chip", "operator": "=~", "value": "/^$chip$/" },
        { "condition": "AND", "key": "feature", "operator": "=~", "value": "/^$feature$/" }
       ]
      },
      {
       "alias": "Max Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "select": [
        [
         { "params": [ "temp_max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "chip", "operator": "=~", "value": "/^$chip$/" },
        { "condition": "AND", "key": "feature", "operator": "=~", "value": "/^$feature$/" }
       ]
      },
      {
       "alias": "Crit Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "select": [
        [
         { "params": [ "temp_crit" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "chip", "operator": "=~", "value": "/^$chip$/" },
        { "condition": "AND", "key": "feature", "operator": "=~", "value": "/^$feature$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Temp - $node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "CPU Temp - $tag_chip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chip" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "query": "SELECT mean(\"temp_input\") FROM \"compunaut_one_year\".\"sensors\" WHERE (\"host\" =~ /^$node$/ AND \"chip\" =~ /^$chip$/ AND \"feature\" = 'core_0') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "temp_input" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "chip", "operator": "=~", "value": "/^$chip$/" },
        { "condition": "AND", "key": "feature", "operator": "=~", "value": "/^$feature$/" }
       ]
      },
      {
       "alias": "Max Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "select": [
        [
         { "params": [ "temp_max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "chip", "operator": "=~", "value": "/^$chip$/" },
        { "condition": "AND", "key": "feature", "operator": "=~", "value": "/^$feature$/" }
       ]
      },
      {
       "alias": "Crit Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "select": [
        [
         { "params": [ "temp_crit" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "chip", "operator": "=~", "value": "/^$chip$/" },
        { "condition": "AND", "key": "feature", "operator": "=~", "value": "/^$feature$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Temp - $node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "alias": "CPU Temp - $tag_chip",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "chip" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "query": "SELECT mean(\"temp_input\") FROM \"compunaut_one_year\".\"sensors\" WHERE (\"host\" =~ /^$node$/ AND \"chip\" =~ /^$chip$/ AND \"feature\" = 'core_0') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "temp_input" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "chip", "operator": "=~", "value": "/^$chip$/" },
        { "condition": "AND", "key": "feature", "operator": "=~", "value": "/^$feature$/" }
       ]
      },
      {
       "alias": "Max Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "select": [
        [
         { "params": [ "temp_max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "chip", "operator": "=~", "value": "/^$chip$/" },
        { "condition": "AND", "key": "feature", "operator": "=~", "value": "/^$feature$/" }
       ]
      },
      {
       "alias": "Crit Temp",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "select": [
        [
         { "params": [ "temp_crit" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "chip", "operator": "=~", "value": "/^$chip$/" },
        { "condition": "AND", "key": "feature", "operator": "=~", "value": "/^$feature$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fan Speed - $node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "repeat": "node",
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "alias": "Fan Speed - $tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ipmi_sensor",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$fan$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Speed - $node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "alias": "Fan Speed - $tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ipmi_sensor",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$fan$/" }
       ]
      }
     ]
    },
    {
     "title": "Fan Speed - $node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "rpm" }
     ],
     "targets": [
      {
       "alias": "Fan Speed - $tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ipmi_sensor",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$fan$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Electric Current",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current - $node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "repeat": "node",
     "yaxes": [
      { "format": "amp" }
     ],
     "targets": [
      {
       "alias": "Current - $tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ipmi_sensor",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$current$/" }
       ]
      }
     ]
    },
    {
     "title": "Current - $node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "amp" }
     ],
     "targets": [
      {
       "alias": "Current - $tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ipmi_sensor",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$current$/" }
       ]
      }
     ]
    },
    {
     "title": "Current - $node",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "amp" }
     ],
     "targets": [
      {
       "alias": "Current - $tag_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ipmi_sensor",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$node$/" },
        { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$current$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}