{
 "title": "Printers",
 "tags": [ "printers" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "octoprint_node",
    "label": "Octoprint Node",
    "query": "SHOW TAG VALUES FROM consul_health_checks WITH KEY = \"node\" WHERE \"service_name\" =~ /compunaut-octoprint/"
   },
   {
    "name": "rundeck_node",
    "label": "Rundeck Node",
    "query": "SHOW TAG VALUES FROM consul_health_checks WITH KEY = \"node\" WHERE \"service_name\" =~ /compunaut-rundeck/"
   },
   {
    "name": "filaments",
    "label": "Filaments",
    "query": "select distinct(filament) from octoprint_custom where time > now() - 20s"
   }
  ]
 },
 "panels": [
  { "title": "Current Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  { "title": "Rundeck Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Running Executions",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "date_started" ], "type": "tag" }
     ],
     "measurement": "rundeck_custom",
     "query": "SELECT last(\"job_name\"), last(\"user\") FROM \"compunaut_one_year\".\"rundeck_custom\" WHERE (\"host\" =~ /^$rundeck_node$/) AND $timeFilter GROUP BY \"date_started\" LIMIT 12",
     "select": [
      [
       { "params": [ "job_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Job Name" ], "type": "alias" }
      ],
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "User" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$rundeck_node$/" }
     ]
    }
   ]
  },
  { "title": "Printer Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Printer Status - $octoprint_node",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "repeat": "octoprint_node",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Octoprint",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "passing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$octoprint_node$/" },
      { "condition": "AND", "key": "service_name", "operator": "=", "value": "compunaut-octoprint" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$octoprint_node$/" }
     ]
    },
    {
     "alias": "Octoprint Critical",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "consul_health_checks",
     "select": [
      [
       { "params": [ "critical" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$octoprint_node$/" },
      { "condition": "AND", "key": "service_name", "operator": "=", "value": "compunaut-octoprint" },
      { "condition": "AND", "key": "node", "operator": "=~", "value": "/^$octoprint_node$/" }
     ]
    },
    {
     "alias": "Operational",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "octoprint_custom",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$octoprint_node$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "operational" }
     ]
    },
    {
     "alias": "Printing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "octoprint_custom",
     "select": [
      [
       { "params": [ "state" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$octoprint_node$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "printing" }
     ]
    },
    {
     "alias": "Bed Actual",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "octoprint_custom",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$octoprint_node$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "bed_actual" }
     ]
    },
    {
     "alias": "Tool Actual",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "octoprint_custom",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$octoprint_node$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "tool_actual" }
     ]
    }
   ]
  },
  { "title": "Job Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Job Progress - $octoprint_node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "repeat": "octoprint_node",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "octoprint_custom",
     "select": [
      [
       { "params": [ "progress" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$octoprint_node$/" },
      { "condition": "AND", "key": "name", "operator": "=", "value": "job_progress" }
     ]
    }
   ]
  },
  { "title": "Filament Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "$filaments",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "repeat": "filaments",
   "targets": [
    {
     "limit": "1",
     "measurement": "octoprint_custom",
     "query": "SHOW TAG VALUES FROM consul_health_checks WITH KEY = \"node\" WHERE \"service_name\" =~ /^$filaments$/",
     "select": [
      [
       { "params": [ "node" ], "type": "field" }
      ],
      [
       { "params": [ "status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "filament_status" },
      { "condition": "AND", "key": "filament_name", "operator": "=~", "value": "/^$filaments$/" }
     ]
    }
   ]
  }
 ]
}