include:
  - compunaut_rundeck.apache
  - compunaut_rundeck.nfs
  - nfs
  - compunaut_rundeck.sudo
  - rundeck.repo
  - rundeck.install
  - rundeck.config
  - rundeck.plugins
  - rundeck.service
  - compunaut_rundeck.uwsgi
  - uwsgi.service
  - uwsgi.applications
  - compunaut_rundeck.config
  - compunaut_rundeck.acl
  - compunaut_rundeck.resources
  - rundeck.client
