include:
  - compunaut_rundeck.sudo
  - rundeck.repo
  - rundeck.install
  - rundeck.config
  - rundeck.plugins
  - rundeck.service
  - compunaut_rundeck.truststore
  - rundeck
  - uwsgi
  - compunaut_rundeck.uwsgi
  - compunaut_rundeck.config
  - compunaut_rundeck.acl
  - compunaut_rundeck.resources
